version: "3.8"

services:
  url-discovery-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-discovery-service
    ports:
      - "8217:8000"
    volumes:
      - .:/app  # 可选：挂载代码目录以便热更新或调试
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

    networks: 
      - audit_network

networks:
  audit_network:
    external: true